
[arch]

# Machine description
nickname        = arch
name            = arch
location        = Arch Linux Docker container
description     = Arch Linux (rolling release) with GCC 14+
status          = personal

# Access / identification
hostname        = arch
aliaspattern    = ^arch$

envsetup = <<EOF
export LIBRARY_PATH="${LIBRARY_PATH+$LIBRARY_PATH:}/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/lib64:/lib"
export CPATH="${CPATH+$CPATH:}/usr/local/include:/usr/include:/include"
EOF

# Source tree management
sourcebasedir   = /home/etuser
optionlist      = arch.cfg
submitscript    = generic.sub
runscript       = generic.run
make            = make -j@MAKEJOBS@
basedir         = /home/etuser/simulations
ppn             = 40
max-num-threads = 40
num-threads     = 20
nodes           = 1
submit          = exec nohup @SCRIPTFILE@ < /dev/null > @RUNDIR@/@SIMULATION_NAME@.out 2> @RUNDIR@/@SIMULATION_NAME@.err & echo $!
getstatus       = ps @JOB_ID@

stop            = pkill -g $(ps -o pgid= -p @JOB_ID@)
submitpattern   = (.*)
statuspattern   = "^ *@JOB_ID@ "
queuedpattern   = $^
runningpattern  = ^
holdingpattern  = $^
exechost        = echo localhost
exechostpattern = (.*)
stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.err
